/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uefs.ecomp.jogodamesada.cliente.view;

import java.awt.Toolkit;
import java.util.Random;

/**
 *
 * @author Gilvanei
 */
public class BarraDeProgresso extends javax.swing.JFrame {

    /**
     * Creates new form BarraDeProgresso
     */
    public BarraDeProgresso() {
        initComponents();
        this.config();
    }

    private void config() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.status.setText("");
        this.setSize(400, 220);
        this.carregaBarra();
        this.start.setVisible(false);
    }

    public void carregaBarra() {
        new Thread() {

            @Override
            public void run() {
                
                Random random = new Random();
                
                for (int i = 0; i <= 100; i++) {
                    try {                       
                        
                        sleep(random.nextInt(120));
                        barra.setValue(i);
                        
                        
                        
                        if(barra.getValue() == 0){
                            status.setText("Recuperando dados de conexão...");
                        }                        
                        if(barra.getValue() == 40){
                            status.setText("Recuperando dados da sala e dos jogadores...");
                        }
                        if(barra.getValue() == 75){
                            status.setText("Recuperando dados de usuário...");
                        }
                        
                        if(barra.getValue() == 100){
                            status.setText("Todos os dados foram recuperados com sucesso!");
                            Toolkit.getDefaultToolkit().beep();
                            start.setVisible(true);
                        }
                    } catch (InterruptedException ignore) {

                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        barra = new javax.swing.JProgressBar();
        tresPontos = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        painel.setBackground(new java.awt.Color(36, 46, 60));

        barra.setBackground(new java.awt.Color(204, 204, 255));
        barra.setForeground(new java.awt.Color(88, 196, 196));
        barra.setStringPainted(true);

        tresPontos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tresPontos.setForeground(new java.awt.Color(204, 204, 204));
        tresPontos.setText(". . .");

        start.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        start.setText("Iniciar Jogo");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Carregando Dados");

        status.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("jLabel2");

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(start)
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tresPontos)
                .addGap(173, 173, 173))
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                    .addContainerGap(0, Short.MAX_VALUE)
                    .addComponent(titulo)
                    .addGap(78, 78, 78)))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tresPontos)
                .addGap(18, 18, 18)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titulo)
                    .addContainerGap(258, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_startActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JPanel painel;
    private javax.swing.JButton start;
    private javax.swing.JLabel status;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tresPontos;
    // End of variables declaration//GEN-END:variables

}
